spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ziyuan?characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.ysd.demo.entity: debug
    
mybatis:
  type-aliases-package: com.ysd.demo.entity
  mapper-locations: classpath:mapper/*.xml